import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
                label: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'tertiary-fixed-dim': '#3adccc',
                'surface-container-lowest': '#001209',
                'on-primary-fixed': '#002022',
                'surface-variant': '#0e3c29',
                'surface-tint': '#00dce6',
                'outline-variant': '#3a494b',
                'surface': '#00180d',
                'tertiary-container': '#58f2e2',
                'on-surface': '#bdedd2',
                'on-secondary-container': '#91bfa6',
                'surface-dim': '#00180d',
                'on-primary-fixed-variant': '#004f53',
                'surface-container-high': '#00311f',
                'error-container': '#93000a',
                'on-error-container': '#ffdad6',
                'on-tertiary-container': '#006c63',
                'inverse-primary': '#00696f',
                'secondary': '#a2d1b7',
                'error': '#ffb4ab',
                'inverse-on-surface': '#083825',
                'background': '#00180d',
                'on-secondary-fixed-variant': '#234f3b',
                'surface-container': '#002517',
                'on-secondary': '#083825',
                'secondary-fixed': '#bdedd2',
                'on-primary-container': '#006b71',
                'on-surface-variant': '#b9cacb',
                'on-background': '#bdedd2',
                'on-secondary-fixed': '#002113',
                'surface-bright': '#14412e',
                'surface-container-low': '#002113',
                'on-error': '#690005',
                'secondary-fixed-dim': '#a2d1b7',
                'primary-container': '#00f3ff',
                'outline': '#849495',
                'on-tertiary-fixed-variant': '#005049',
                'primary': '#e3fdff',
                'tertiary-fixed': '#61f9e9',
                'secondary-container': '#234f3b',
                'primary-fixed': '#6ff6ff',
                'tertiary': '#ddfff9',
                'on-tertiary-fixed': '#00201d',
                'on-tertiary': '#003732',
                'surface-container-highest': '#0e3c29',
                'on-primary': '#00373a',
                'inverse-surface': '#bdedd2',
                'primary-fixed-dim': '#00dce6',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                full: '9999px',
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            },
        },
    },

    plugins: [forms],
};
